//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace JBClasses
{
	public enum JBCharacters
	{
		JUNGLEBEE,
		CARPENTERBEE,
		BUMBLEBEE,
		KILLERBEE
	}
	public enum BossWeapon
	{
		stinger,
		spear,
		mouth,
		yap,
		sword,
		net,
		complex,
		none
	}
	public enum EnemyWeapon
	{
		stinger,
		spear,
		none
	}
	public enum EnemyExistPlace
	{
		sky,
		land,
		land_sky,
		none
	}
	public enum MovingMode
	{
		flying,
		crawling,
		walking,
		spread,
		hanging,
		wraping,
		none
	}
	public enum JBItem
	{
		HONEY,
		HEART,
		FLOWER,
		KISS
	}
	public enum BossExistType
	{
		SKY,
		LAND,
		LAND_SKY,
		STATIC,
		NONE
	}
	public enum BossAttackMode
	{
		ONLY_ATTACK,
		ONLY_HONEY,
		ATTACK_HONEY
	}
	public enum ObstacleType
	{
		Falling_Rock,
		Static_Rock,
		Rolling_Rock,
		Plant,
		Gas,
		Spining_Razor,
        SubBomb,
	}
}

